--- #YAML:1.0
# http://module-build.sourceforge.net/META-spec.html
name: SVN-Hooks
abstract: Framework for implementing Subversion hooks.
version: 0.24
author: Gustavo Chaves <gnustavo@cpan.org>
license: perl
generated_by: Gustavo Chaves
distribution_type: module
requires:
  Test::More: 0
  SVN::Look: 0.10
optional_features:
- Jira::Client:
    description: An extended interface to JIRAs SOAP API.
    requires:
      SOAP::Lite: 0
- JiraAcceptance:
    description: Plugin to integrate Subversion with the JIRA ticketing system.
    requires:
      XMLRPC::Lite: 0
- Mailer:
    description: Plugin to send emails after succesful commits.
    requires:
      Email::Send: 0
      Email::Simple: 0
      Email::Simple::Creator: 0
- Notify:
    description: Plugin to send emails after succesful commits.
    requires:
      SVN::Notify: 0
provides:
  SVN::Hooks::AllowLogChange:
    file: lib/SVN/Hooks/AllowLogChange.pm
  SVN::Hooks::CheckJira:
    file: lib/SVN/Hooks/CheckJira.pm
  SVN::Hooks::CheckLog:
    file: lib/SVN/Hooks/CheckLog.pm
  SVN::Hooks::CheckMimeTypes:
    file: lib/SVN/Hooks/CheckMimeTypes.pm
  SVN::Hooks::CheckProperty:
    file: lib/SVN/Hooks/CheckProperty.pm
  SVN::Hooks::CheckStructure:
    file: lib/SVN/Hooks/CheckStructure.pm
  SVN::Hooks::DenyChanges:
    file: lib/SVN/Hooks/DenyChanges.pm
  SVN::Hooks::DenyFilenames:
    file: lib/SVN/Hooks/DenyFilenames.pm
  SVN::Hooks::JiraAcceptance:
    file: lib/SVN/Hooks/JiraAcceptance.pm
  SVN::Hooks::Mailer:
    file: lib/SVN/Hooks/Mailer.pm
  SVN::Hooks::Notify:
    file: lib/SVN/Hooks/Notify.pm
  SVN::Hooks::UpdateConfFile:
    file: lib/SVN/Hooks/UpdateConfFile.pm
resources:
  license: http://dev.perl.org/licenses/
