--- #YAML:1.0
name: SVN-Hooks
abstract: Framework for implementing Subversion hooks.
version: 1.03
author: Gustavo Chaves <gnustavo@cpan.org>
license: perl
generated_by: Gustavo Chaves
distribution_type: module
requires:
  perl: 5.008
  Test::More: 0
  SVN::Look: 0.21
build_requires:
  URI::file: 0
optional_features:
- Jira::Client:
    description: An extended interface to JIRAs SOAP API.
    requires:
      SOAP::Lite: 0
- JiraAcceptance:
    description: Plugin to integrate Subversion with the JIRA ticketing system.
    requires:
      XMLRPC::Lite: 0
- Mailer:
    description: Plugin to send emails after succesful commits.
    requires:
      Email::Send: 0
      Email::Simple: 0
      Email::Simple::Creator: 0
- Notify:
    description: Plugin to send emails after succesful commits.
    requires:
      SVN::Notify: 0
provides:
  SVN::Hooks::AllowLogChange:
    file: lib/SVN/Hooks/AllowLogChange.pm
  SVN::Hooks::AllowPropChange:
    file: lib/SVN/Hooks/AllowPropChange.pm
  SVN::Hooks::CheckCapability:
    file: lib/SVN/Hooks/CheckCapability.pm
  SVN::Hooks::CheckJira:
    file: lib/SVN/Hooks/CheckJira.pm
  SVN::Hooks::CheckLog:
    file: lib/SVN/Hooks/CheckLog.pm
  SVN::Hooks::CheckMimeTypes:
    file: lib/SVN/Hooks/CheckMimeTypes.pm
  SVN::Hooks::CheckProperty:
    file: lib/SVN/Hooks/CheckProperty.pm
  SVN::Hooks::CheckStructure:
    file: lib/SVN/Hooks/CheckStructure.pm
  SVN::Hooks::DenyChanges:
    file: lib/SVN/Hooks/DenyChanges.pm
  SVN::Hooks::DenyFilenames:
    file: lib/SVN/Hooks/DenyFilenames.pm
  SVN::Hooks::Generic:
    file: lib/SVN/Hooks/Generic.pm
  SVN::Hooks::JiraAcceptance:
    file: lib/SVN/Hooks/JiraAcceptance.pm
  SVN::Hooks::Mailer:
    file: lib/SVN/Hooks/Mailer.pm
  SVN::Hooks::Notify:
    file: lib/SVN/Hooks/Notify.pm
  SVN::Hooks::UpdateConfFile:
    file: lib/SVN/Hooks/UpdateConfFile.pm
resources:
  license: http://dev.perl.org/licenses/
  homepage: http://code.google.com/p/svn-hooks/
  repository: http://svn-hooks.googlecode.com/svn/trunk/
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
